@startuml
participant _validateAccountAndPaymasterValidationData
participant _getValidationData

_validateAccountAndPaymasterValidationData <-> _getValidationData: 1- 签名验证sender回调的validationData
_validateAccountAndPaymasterValidationData <-> _getValidationData: 2- 签名验证paymaster的validationData

' function _packValidationData(bool sigFailed, uint48 validUntil, uint48 validAfter) pure returns (uint256) {
'    return (sigFailed ? 1 : 0) | (uint256(validUntil) << 160) | (uint256(validAfter) << (160 + 48));
'}
@enduml
